# Generated by Django 3.2 on 2021-05-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='date_hired',
            new_name='data_de_contratacao',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='phone',
            new_name='telefone',
        ),
    ]
