# Generated by Django 3.2 on 2021-05-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_corretor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corretor',
        ),
    ]
